### ISSUE TITLE
newIntronRetention error

### ISSUE THREAD

**Issue by trptyrphe** [pachterlab/kma#12]
computing denominator
Error in summarise_impl(.data, dots): invalid 'type' (character) of argument
Traceback:

1. newIntronRetention(xprs$tpm, intron_to_trans, xprs$condition)
2. left_join(intronToUnion, targetExpression, by = "target_id") %>% 
 .     group_by(intron) %>% select(-(target_id)) %>% summarise_each(funs(sum), 
 .     -matches("gene"), -matches("intron_extension")) %>% arrange(intron) %>% 
 .     left_join(select(intronToUnion, intron, intron_extension) %>% 
 .         distinct(), by = c("intron"))
3. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
4. eval(quote(`_fseq`(`_lhs`)), env, env)
5. eval(expr, envir, enclos)
6. `_fseq`(`_lhs`)
7. freduce(value, `_function_list`)
8. function_list[[i]](value)
9. summarise_each(., funs(sum), -matches("gene"), -matches("intron_extension"))
10. summarise_each_(tbl, funs, lazyeval::lazy_dots(...))
11. summarise_(tbl, .dots = vars)
12. summarise_.tbl_df(tbl, .dots = vars)
13. summarise_impl(.data, dots)

**Comment by edkonyakhina** [comment]
Hello, @trptyrphe11!
Did you find a solution of your problem? 
I have the same.
